package stradar.organizationview.createstrategy.internal

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Schema
import java.util.UUID
import java.util.concurrent.ExecutionException
import mu.KotlinLogging
import org.axonframework.commandhandling.CommandExecutionException
import org.axonframework.commandhandling.gateway.CommandGateway
import org.axonframework.messaging.MetaData
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import stradar.common.CommandException
import stradar.common.StrategyStatus
import stradar.organizationview.domain.commands.createstrategy.CreateStrategyCommand
import stradar.support.metadata.*

/** Payload for creating a strategy. strategyId is generated by the backend. */
data class CreateStrategyPayload(
    @Schema(
        description = "The team this strategy belongs to",
        example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    val teamId: UUID,
    @Schema(description = "The organization context") val organizationId: UUID,
    @Schema(description = "The title of the strategy", example = "2026 Growth Plan")
    val title: String,
    @Schema(description = "The timeframe for this strategy", example = "Q1-Q4 2026")
    val timeframe: String,
    @Schema(description = "The status of the strategy", example = "DRAFT") val status: String
)

@RestController
@RequestMapping("/api/v1/strategies")
class CreateStrategyResource(private val commandGateway: CommandGateway) {

  private val logger = KotlinLogging.logger {}

  @CrossOrigin(
      allowedHeaders =
          [
              ORGANIZATION_ID_HEADER,
              SESSION_ID_HEADER,
              "Content-Type",
              "X-Correlation-Id",
              USER_ID_HEADER])
  @PostMapping
  @Operation(summary = "Create a new strategy slot for a team")
  fun createStrategy(
      @RequestHeader(value = "X-Correlation-Id", required = false) correlationId: String?,
      @RequestHeader(value = SESSION_ID_HEADER, required = true) sessionId: String,
      @RequestHeader(value = USER_ID_HEADER, required = true) userId: String,
      @RequestBody payload: CreateStrategyPayload
  ): ResponseEntity<Any> {

    val strategyBuilderId = "${payload.teamId}-STRATEGY-BUILDER"
    val newStrategyId = UUID.randomUUID()

    val strategyStatus =
        try {
          StrategyStatus.valueOf(payload.status.uppercase())
        } catch (ex: IllegalArgumentException) {
          throw IllegalArgumentException("Invalid strategy status: ${payload.status}")
        }

    logger.info {
      "Creating strategy $newStrategyId for builder $strategyBuilderId with status $strategyStatus"
    }

    val metadata =
        MetaData.with(USER_ID_HEADER, userId)
            .and("X-Correlation-Id", correlationId ?: UUID.randomUUID().toString())
            .and(SESSION_ID_HEADER, sessionId)
            .and(ORGANIZATION_ID_HEADER, payload.organizationId)

    val command =
        CreateStrategyCommand(
            strategyBuilderId = strategyBuilderId,
            teamId = payload.teamId,
            organizationId = payload.organizationId,
            strategyId = newStrategyId,
            strategyName = payload.title,
            strategyTimeframe = payload.timeframe,
            strategyStatus = strategyStatus)

    return try {
      val result = commandGateway.send<Any>(command, metadata).get()
      ResponseEntity.ok(result)
    } catch (ex: ExecutionException) {
      val cause = ex.cause
      logger.warn { "CreateStrategy failed: ${cause?.message ?: ex.message}" }
      when {
        cause is CommandExecutionException && cause.cause is CommandException ->
            throw cause.cause as CommandException
        cause is CommandException -> throw cause
        cause is CommandExecutionException ->
            throw CommandException(cause.message ?: "Command execution failed")
        cause != null -> throw cause
        else -> throw ex
      }
    }
  }
}
