# DataSource Configuration
spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-stradar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres-stradar
    locations: classpath:db/migration
    user: postgres
    password: postgres
    baseline-on-migrate: true
    baseline-version: 20240101

axon:
  serializer:
    general: jackson
  axonserver:
    enabled: false
  eventhandling:
    processors:
      ORGANIZATION_VIEW:
        mode: tracking
      ENVIRONMENTAL_CHANGES_VIEW:
        mode: tracking
      PLATFORM_ADMINISTRATION:
        mode: tracking

#axoniq:
#  console:
#    application-name: Awesome-Microservice
#    credentials: <token> #https://console.axoniq.io/
#    dlq-mode: NONE

application:
  debug:
    enabled: true
