spring:
  profiles:
    active: dev

  application:
    name: stradar

server:
  port: 8080

logging:
  level:
    root: INFO

axon:
  updates:
    enabled: false
  serializer:
    general: jackson
  axonserver:
    enabled: false
  eventhandling:
    processors:
      ORGANIZATION_VIEW:
        mode: tracking
      ENVIRONMENTAL_CHANGES_VIEW:
        mode: tracking
      PLATFORM_ADMINISTRATION:
        mode: tracking

application:
  debug:
    enabled: true