package stradar.strategy.internal

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Schema
import java.util.UUID
import java.util.concurrent.CompletableFuture
import mu.KotlinLogging
import org.axonframework.commandhandling.gateway.CommandGateway
import org.axonframework.messaging.MetaData
import org.springframework.web.bind.annotation.*
import stradar.organizationview.domain.commands.createdraftstrategy.CreateDraftStrategyCommand
import stradar.support.metadata.SESSION_ID_HEADER

/**
 * Payload for creating a strategy. Note: strategyId is generated by the backend to ensure
 * uniqueness.
 */
data class CreateStrategyPayload(
        @Schema(
                description = "The team this strategy belongs to",
                example = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        )
        val teamId: UUID,
        @Schema(description = "The organization context") val organizationId: UUID,
        @Schema(description = "The title of the strategy", example = "2026 Growth Plan")
        val title: String,
        @Schema(description = "The timeframe for this strategy", example = "Q1-Q4 2026")
        val timeframe: String
)

@RestController
@RequestMapping("/api/v1/strategies")
class StrategyResource(private val commandGateway: CommandGateway) {

        private val logger = KotlinLogging.logger {}

        @CrossOrigin(
                allowedHeaders =
                        [
                                "organizationId",
                                SESSION_ID_HEADER,
                                "Content-Type",
                                "X-Correlation-Id",
                                "x-user-id"]
        )
        @PostMapping("/draft")
        @Operation(summary = "Create a new Draft Strategy slot for a team")
        fun createDraft(
                @RequestHeader(value = "X-Correlation-Id", required = false) correlationId: String?,
                @RequestHeader(value = SESSION_ID_HEADER, required = true) sessionId: String,
                @RequestHeader(value = "x-user-id", required = true) userId: String,
                @RequestBody payload: CreateStrategyPayload
        ): CompletableFuture<Any> {

                // ID Derivation: Creating the technical "Slot" ID
                val strategyBuilderId = "${payload.teamId}-STRATEGY-BUILDER"

                // Instance Generation: Creating the unique ID for this specific Strategy version
                val newStrategyId = UUID.randomUUID()

                logger.info {
                        "Creating draft strategy $newStrategyId for builder $strategyBuilderId"
                }

                val metadata =
                        MetaData.with("x-user-id", userId)
                                .and(
                                        "X-Correlation-Id",
                                        correlationId ?: UUID.randomUUID().toString()
                                )
                                .and(SESSION_ID_HEADER, sessionId)
                                .and("organizationId", payload.organizationId)

                // Mapping payload to the Command + Nested StrategyDetails Value Object
                val command =
                        CreateDraftStrategyCommand(
                                strategyBuilderId = strategyBuilderId,
                                teamId = payload.teamId,
                                organizationId = payload.organizationId,
                                strategyId = newStrategyId,
                                strategyName = payload.title,
                                strategyTimeframe = payload.timeframe
                        )

                return commandGateway.send<Any>(command, metadata)
        }
}
